In [3]:
#import the library
import numpy


In [6]:
##initializing a matyrix using the numpy array
A = numpy.array([[1,2],[2,4]])
B = numpy.array([[3,4],[5,6]])

In [9]:
print(A)


[[1 2]
 [2 4]]


In [8]:
print(B)

[[3 4]
 [5 6]]


In [10]:
##Vector multplication
c = numpy.array([[5,2,9],[4,6,7],[1,3,8]])
d = numpy.array([[1],[2],[4]])
result = numpy.dot(c,d)
print(result)

[[45]
 [44]
 [39]]


In [11]:
##Vector multplication
e = numpy.array([[5,2,9],[4,6,7],[1,3,8]])
f = numpy.array([[1,2],[2,1],[1,2]])
result = numpy.dot(e,f)
print(result)

[[18 30]
 [23 28]
 [15 21]]


In [12]:
##Vector multplication
g = numpy.array([[5,2,9],[4,6,7],[1,3,8]])
h = numpy.array([[1,2,1],[3,1,2],[4,2,1]])
result = numpy.dot(g,h)
print(result)

[[47 30 18]
 [50 28 23]
 [42 21 15]]


In [15]:
 N = numpy.array([[3],[2],[8]])
 M = numpy.array([[2],[9],[7]])
 # transposr the array, because the parameter must be in dimentions 2 or 3
 cross = np.cross(np.transpose(N),np.transpose(M))
 print(cross)

 ## if i can ask


[[-58  -5  23]]


In [17]:
K = numpy.array([[1,1,0],[2,1,2]])
transpose = numpy.transpose(K)
print(transpose)

[[1 2]
 [1 1]
 [0 2]]


In [18]:
 Q = numpy.array([[2,1],[4,3]])
 inverse = numpy.linalg.inv(Q)
 print(inverse)

[[ 1.5 -0.5]
 [-2.   1. ]]


In [19]:
R = numpy.array([[1,1,2],[2,1,2],[2,3,1]])
inverse = numpy.linalg.inv(R)
print(inverse)


[[-1.   1.   0. ]
 [ 0.4 -0.6  0.4]
 [ 0.8 -0.2 -0.2]]


In [20]:
#Rank of the matrix
P = numpy.array([[1,1,2],[2,1,2],[2,3,1]])
rank = numpy.linalg.matrix_rank(P)
print(rank)

3


In [21]:
P = numpy.array([[1,2,3],[2,1,2],[2,4,6]])
rank = numpy.linalg.matrix_rank(P)
print("rank of the matrix H is: " + str(rank))


rank of the matrix H is: 2


In [30]:
## LU Decomposition
from scipy.linalg import lu
A = numpy.array([[1,2,3],[2,1,2],[2,4,6]])
P, L, U = lu(A)

In [31]:
print(P)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [32]:
print(L)

[[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.5 1. ]]


In [33]:
print(U)

[[2. 1. 2.]
 [0. 3. 4.]
 [0. 0. 0.]]


In [35]:
result =P.dot(L).dot(U)
print(result)

[[1. 2. 3.]
 [2. 1. 2.]
 [2. 4. 6.]]


In [36]:
## QR Decomposition
from numpy.linalg import qr

In [37]:
S = numpy.array([[1,2,3],[2,1,2],[2,4,6]])
Q, R = qr(S)

In [38]:
print(Q)

[[-0.33333333  0.2981424  -0.89442719]
 [-0.66666667 -0.74535599  0.        ]
 [-0.66666667  0.59628479  0.4472136 ]]


In [39]:
print(R)

[[-3.00000000e+00 -4.00000000e+00 -6.33333333e+00]
 [ 0.00000000e+00  2.23606798e+00  2.98142397e+00]
 [ 0.00000000e+00  0.00000000e+00  8.88178420e-16]]


In [40]:
result = Q.dot(R)
print(result)

[[1. 2. 3.]
 [2. 1. 2.]
 [2. 4. 6.]]


In [41]:
##cholesky Decomposition
from numpy.linalg import cholesky


In [43]:
D2 = numpy.array([[2,1,1],[1,2,1],[1,1,2]])
L = cholesky(D2)
T = numpy.transpose(L)

In [44]:
print(L)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [45]:
result = L.dot(T)
print(result)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [46]:
## Eigen value and eigen Vectors

In [47]:
M = numpy.array([[5,2],[2,1]])
eigenvalues, eigenvectors = numpy.linalg.eig(M)

In [49]:
print(eigenvalues)


[5.82842712 0.17157288]


In [50]:
print(eigenvectors)

[[ 0.92387953 -0.38268343]
 [ 0.38268343  0.92387953]]


In [51]:
import numpy as np
import seaborn as sns